spring.application.name=savora

spring.datasource.url=jdbc:postgresql://localhost:5432/savora
spring.datasource.username=dev
spring.datasource.password=dev

spring.flyway.enabled=true

spring.data.mongodb.uri=mongodb://localhost:27017/savora
